### ISSUE TITLE
Waiting wizard to connect

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-wizard#31]
When I install cordova-sentry@0.15.0, it auto-lunches the wizard in the browser but it stucks on "waiting wizard to connect". What can I do?

**Comment by Ng-India99** [comment]
yes i am also facing the same issue how to resolve ?

**Comment by igortupini** [comment]
Same issue here. I'm stuck on this

**Comment by Ng-India99** [comment]
i resolved this issue by installing the sentry wizard globally and call the wizard like below.

$ npm install -g @sentry/wizard
$ sentry-wizard

then follow the instructions

**Comment by igortupini** [comment]
> i resolved this issue by installing the sentry wizard globally and call the wizard like below.
> 
> $ npm install -g @sentry/wizard
> $ sentry-wizard
> 
> then follow the instructions

Thanks. This solve my problem

**Comment by elisechant** [comment]
<img width="483" alt="Screen Shot 2019-09-08 at 5 01 19 am" src="https://user-images.githubusercontent.com/2195815/64479125-c1324280-d1f5-11e9-8c60-144519e9bab6.png">

still an issue on these specs:

```
$ » node_modules/.bin/react-native info   
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 129.17 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.0
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-csv750: 1.0.0
```

**Comment by elisechant** [comment]
Using the `--skip-connect` flag worked for me:

```yarn sentry-wizard -i reactNative -p ios android --skip-connect --debug```

**Comment by jaz-ortizv** [comment]
I'm in windows, the problem was that the documentation send ios and android, just do the 
`yarn sentry-wizard` and select only android. 
![image](https://user-images.githubusercontent.com/56445036/70275517-e6dad380-1773-11ea-804f-5727492d1420.png)

**Comment by vlafranca** [comment]
Hi, for me disabling avast antivirus made it work :)

**Comment by arthedza** [comment]
> I'm in windows, the problem was that the documentation send ios and android, just do the
> `yarn sentry-wizard` and select only android.
> ![image](https://user-images.githubusercontent.com/56445036/70275517-e6dad380-1773-11ea-804f-5727492d1420.png)

npx sentry-wizard is worked too

**Comment by mustafahafidi** [comment]
Same for `--integration electron`, stuck on "Waiting for wizard to connect"

**Comment by waqaramjad** [comment]
same here react native below 0.60

**Comment by samuk190** [comment]
react-native 0.63.1 working after
yarn global add @sentry/wizard
after that sentry-wizard

**Comment by Awais6** [comment]
> i resolved this issue by installing the sentry wizard globally and call the wizard like below.
> 
> $ npm install -g @sentry/wizard
> $ sentry-wizard
> 
> then follow the instructions

Thank You

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by SleeplessByte** [comment]
@kamilogorek I doubt this is fixed given all the posts above and no associated commit.

**Comment by Kaijonsson** [comment]
@kamilogorek 
I'm stuck on waiting :(
Tried all of the above answers. :(

**Comment by Lms24** [comment]
Hi we changed quite a bit in the wizard since the last answer here. Is anyone still facing this issue? Please also let us know which SDK you're setting up. Thanks!

**Comment by miladdev85** [comment]
```npx @sentry/wizard@latest -s -i reactNative``` gives me the following error:



```
Running Sentry Wizard...
version: 3.14.1 | sentry-cli version: 1.75.2
..................
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on PassThrough instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by krystofwoldrich** [comment]
@miladdev85 Thanks for the message and we are happy it works now.

**Comment by Lms24** [comment]
I'm gonna close this issue, given that we heard nothing that needs fixing since my last [reply](https://github.com/getsentry/sentry-wizard/issues/31#issuecomment-1707235452). Please feel free to tag me or open a new issue if you're still experiencing problems with connecting to the wizard. Thanks!

**Comment by VMBindraban** [comment]
> `npx @sentry/wizard@latest -s -i reactNative` gives me the following error:
> 
> ```
> Running Sentry Wizard...
> version: 3.14.1 | sentry-cli version: 1.75.2
> ..................
> node:events:505
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
> Emitted 'error' event on PassThrough instance at:
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -54,
>   code: 'ECONNRESET',
>   syscall: 'read'
> }
> ```
> 
> Edit: I updated Node to latest and it's working now.

Which version of Node were you using? Seems to break in 16.

**Comment by Lms24** [comment]
I can't reproduce this with Node 14, 16 or higher, sorry. Any chance that your network is blocking requests?

**Comment by VMBindraban** [comment]
I used the `--skip-connect` flag. I am currently using 16 and i am not blocking any connections.
Could it be a OS related bug? (macos)

**Comment by Lms24** [comment]
@VMBindraban I also tried this with `--skip-connect` and got through the entire RN wizard: 

![image](https://github.com/getsentry/sentry-wizard/assets/8420481/79dc7530-998e-4829-b3a4-a5e761aaa109)

(I don't have an actual RN test project, which is why some of the steps failed)

I can't get your error message with this command. I'm also on MacOs btw.

**Comment by VMBindraban** [comment]
Interestingly enough while `npx @sentry/wizard -s -i reactNative` doesn't work, using `npx @sentry/wizard` works. 
When using my phone as internet provider both work.

Doesn't work:
```
projectRoot/android [ npx @sentry/wizard -s -i reactNative --verbose                                                                                                                                                                                main * ] 10:17 AM
Running Sentry Wizard...
version: 3.15.0 | sentry-cli version: 1.75.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
no URL provided, fallback to https://sentry.io/
? Select the platforms you like to set up: (Press <space> to select, <a> to toggle all, <i> to invert selection)iOS, Android


Please open
https://sentry.io/account/settings/wizard/***/?signup=1&project_platform=react-native
in your browser (if it's not open already)

/
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on PassThrough instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
```

Works:
```
projectRoot/android [ npx @sentry/wizard                                                                                                                                                                                                            main * ] 10:22 AM
Running Sentry Wizard...
version: 3.15.0 | sentry-cli version: 1.75.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
? What platform do you want to set up? React Native
no URL provided, fallback to https://sentry.io/
? Select the platforms you like to set up: (Press <space> to select, <a> to toggle all, <i> to invert selection)iOS, Android


Please open
https://sentry.io/account/settings/wizard/***/
in your browser (if it's not open already)



✗ react-native isn't in your dependencies.
  Please install it with yarn/npm.
```

**Comment by Lms24** [comment]
> When using my phone as internet provider both work
Hmm so it seems like something is blocking things on your regular network? 🤔

**Comment by VMBindraban** [comment]
> > When using my phone as internet provider both work
> > Hmm so it seems like something is blocking things on your regular network? 🤔

The issue seems to be in the `-s` flag. Without it, it works.

**Comment by VMBindraban** [comment]
Well i don't know why but i broke everything. I logout of Sentry and since than i keep getting the `ECONNRESET` error.

**Comment by lucas-zimerman** [comment]
Odd that I am facing the same issue, but I noticed that only on MacOS it's triggering the error, on windows for the same project (and network) it's working just fine.

I also noticed that the wizard website is stucked on "Waiting for wizard to connect" and keeps calling this url nonstop
`URL: https://sentry.io/api/0/wizard/n2tfi60puktlwc7h2g9u1blsuj6shk3agz1f4wslivr3fowzl7srjpsgibguey6c/`
